MSVC: fix conversion of paths to strings
c_str() yields a path::value_type*, which is a wchar_t on Windows, and
that one cannot be fed to lyd_parse_data_path directly:

 src\Context.cpp(147,16): error C2664: 'LY_ERR lyd_parse_data_path(const ly_ctx *,const char *,LYD_FORMAT,uint32_t,uint32_t,lyd_node **)': cannot convert argument 2 from 'const std::filesystem::path::value_type *' to 'const char *'

Change-Id: I6ea01858990e8fe3aeabfca60bbc24f0bd5bcb0b