MSVC: Make unmanaged_tag fully defined
For some reason MSVC doesn't like our `using` syntax for constructors.
Perhaps that's because the DataNode one is not an implicit one, but the
one for DataNodeTerm is autogenerated by the compiler?

 libyang-cpp\include\libyang-cpp/DataNode.hpp(187): error C2027: use of undefined type 'libyang::unmanaged_tag' [build-libyang-cpp\yang-cpp.vcxproj]
 libyang-cpp\include\libyang-cpp/DataNode.hpp(33): message : see declaration of 'libyang::unmanaged_tag' [build-libyang-cpp\yang-cpp.vcxproj]
 libyang-cpp\include\libyang-cpp/DataNode.hpp(187): message : This diagnostic occurred in the compiler generated function 'libyang::DataNodeTerm::DataNodeTerm(lyd_node *,const libyang::unmanaged_tag)' [build-libyang-cpp\yang-cpp.vcxproj]
 libyang-cpp\include\libyang-cpp/DataNode.hpp(188,1): message : see reference to function 'libyang::DataNodeTerm::DataNodeTerm(lyd_node *,const libyang::unmanaged_tag)' [build-libyang-cpp\yang-cpp.vcxproj]

Change-Id: I511045436ac66cd68e982e490c377d35aaa5a864