tests: cast unused return value of a function to void
In gcc14, this compile error appeared:

  libyang-cpp/tests/data_node.cpp:1286:13: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
   1286 |             std::any_of(set.begin(), set.end(), [](const auto& node) { node.path(); return true; });

It seems that gcc now starts complaining about std::any_of's
nodiscard attribute. We can fix this error by casting the
return value to void [1].

[1] https://en.cppreference.com/w/cpp/language/attributes/nodiscard

Change-Id: Ia37efd6f8842d91c7b97a96f864c318739f0dd71